### ISSUE TITLE
Failing in jenkins due to javax.imageio.IIOException: Incompatible color conversion

### ISSUE THREAD

**Issue by bicschneider** [Praqma/docker-image-size-checker#1]
http://code.praqma.net/ci/job/Web_www.code-conf.com-image-size-checker/3/console

```
+ pwd
+ docker run -u jenkins --rm -v /home/praqma/jenkins-slave/workspace/Web_www.code-conf.com-image-size-checker:/home/jenkins/site/ praqma/image-size-checker groovy /home/jenkins/imageSizeChecker.groovy
Caught: javax.imageio.IIOException: Incompatible color conversion
javax.imageio.IIOException: Incompatible color conversion
    at com.sun.imageio.plugins.jpeg.JPEGImageReader.checkColorConversion(JPEGImageReader.java:973)
    at com.sun.imageio.plugins.jpeg.JPEGImageReader.readInternal(JPEGImageReader.java:1078)
    at com.sun.imageio.plugins.jpeg.JPEGImageReader.read(JPEGImageReader.java:1034)
    at imageSizeChecker$_run_closure1.doCall(imageSizeChecker.groovy:18)
    at imageSizeChecker.run(imageSizeChecker.groovy:14)
Build step 'Execute shell' marked build as failure
Checking console output
Started calculate disk usage of build
Finished Calculation of disk usage of build in 0 seconds
Started calculate disk usage of workspace
```

**Comment by illus0r** [comment]
Hi, @bicschneider!
Thanks for catching the bug.
I've added image names printing in the consol output. So now it will be easier to catch and replace broken images.
Sure, I've found the problem image and replaced it with regenerated one, so the job works by now

![image](https://cloud.githubusercontent.com/assets/797993/17556149/0925b438-5f1b-11e6-9e9d-0da0d136d5a1.png)
